/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-03-05 13:47:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import java.util.Date;
import java.net.*;
import java.io.*;
import org.json.*;
import java.lang.Object.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("java.lang.Object");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>PÁGINA INICIAL</title>\r\n");
      out.write("<script src=\"bootstrap/jquery/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"jQuery Mask/jquery.mask.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"homecss.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"img/logo.png\" />\r\n");
      out.write("<style>\r\n");
      out.write(".celular {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular .screen {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttransition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular:hover .screen.screen5 {\r\n");
      out.write("\ttransform: translateY(-160px);\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular:hover .screen.screen4 {\r\n");
      out.write("\ttransform: translateY(-1);\r\n");
      out.write("\topacity: .8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular:hover .screen.screen3 {\r\n");
      out.write("\ttransform: translateY(-80px);\r\n");
      out.write("\topacity: .6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular:hover .screen.screen2 {\r\n");
      out.write("\ttransform: translateY(-40px);\r\n");
      out.write("\topacity: .4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".celular:hover .screen.screen1 {\r\n");
      out.write("\ttransform: translateY(0px);\r\n");
      out.write("\topacity: .2;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"conteudo\">\r\n");
      out.write("\t");

		String nb = "nobody";
		String whois = (session.getAttribute("usuario") == null) ? "{\"nobody\":"+nb+"}" : session.getAttribute("usuario").toString();
		JSONObject j = new JSONObject(whois);
		String saldo = "";

		if(!whois.equals("{\"nobody\":"+nb+"}")){
			String n = j.getString("numero_conta");
			j.put("numero_conta", n);
			
			String teste = "teste";
			
			if(teste.equals("teste")){
				URL url = new URL("http://10.87.207.6:8080/WebService/service");
				
				HttpURLConnection con = (HttpURLConnection) url.openConnection();
				con.setRequestMethod("POST");
				con.setDoOutput(true);
				
				String parametros = "id=2&tipo=2&valores="+j.toString();
				DataOutputStream wr = new DataOutputStream(con.getOutputStream());
				wr.writeBytes(parametros);
				
				BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
				
				String apnd = "", linha = "";
				
				while((linha = br.readLine()) != null) apnd += linha;
				
				JSONObject obj = new JSONObject(apnd);
				saldo = obj.getString("saldo");
			}
		}
		
		String tipo = request.getParameter("tipo");
		
		if(tipo != null){
			if(tipo.equals("6")){
				URL url = new URL("http://10.87.207.6:8080/WebService/service");
				
				String cpf = request.getParameter("cpf");
				String cpf1 = cpf.replace(".", "");
				String cpfzao = cpf1.replace("-", "");
				
				String senhaAcesso = request.getParameter("senhaAcessoLogin");
				String sair = request.getParameter("sair");
				
				JSONObject json = new JSONObject();
				json.put("documento", cpfzao);
				json.put("senhaAcesso", senhaAcesso);
					
				HttpURLConnection con = (HttpURLConnection) url.openConnection();
				con.setRequestMethod("POST");
				con.setDoOutput(true);
				
				String parametros = "id=2&tipo=6&valores="+json.toString();
				DataOutputStream wr = new DataOutputStream(con.getOutputStream());
				wr.writeBytes(parametros);
				
				BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
				
				String apnd = "", linha = "";
				
				while((linha = br.readLine()) != null) apnd += linha;
				
				JSONObject jon = new JSONObject(apnd);
				
				if(jon.has("cod")){
					int cod = jon.getInt("cod");
					
					if(cod == 101){
						out.print("<script>alert('Parâmetros fora do escopo.')</script>");
					}else if(cod == 102){
						out.print("<script>alert('Senha de acesso invalida.')</script>");
					}else if(cod == 103){
						out.print("<script>alert('CPF Inválido.')</script>");
					}else if(cod == 104){
						out.print("<script>alert('Data inválida.')</script>");
					}else if(cod == 105){
						out.print("<script>alert('Falha ao inserir.')</script>");
					}else if(cod == 106){
						out.print("<script>alert('CPF inválido.')</script>");
					}else if(cod == 001){
						out.print("<script>alert('Tipo não informado.')</script>");
					}else if(cod == 002){
						out.print("<script>alert('Valores não recebidos.')</script>");
					}else if(cod == 003){
						out.print("<script>alert('ID não informado.')</script>");
					}else if(cod == 007){
						out.print("<script>alert('Campo não encontrado.')</script>");
					}else{
						out.print("<script>alert('Conta não existe.')</script>");
					}
				}else{
					String nome = jon.getString("nome");
					String numero = jon.getString("numero_conta");
					HttpSession hs = request.getSession();
					hs.setAttribute("usuario", apnd);	
					response.sendRedirect("home.jsp");
				}
			}else{
				HttpSession hs = request.getSession();
				hs.invalidate();
				response.sendRedirect("home.jsp");
			}
		}
		
		String tipagem = request.getParameter("tipagem");
		String recebedor = "";
		
		if(tipagem != null){
			String nome = request.getParameter("nome");
			
			String cpf = request.getParameter("cpf");
			String cpf1 = cpf.replace(".", "");
			String cpfzao = cpf1.replace("-", "");
			
			String dataNasc = request.getParameter("dataNasc");
			String dataNasc1 = dataNasc.replace("/", "");
			
			String endereco = request.getParameter("endereco");
			
			String telefone = request.getParameter("telefone");
			String tel1 = telefone.replace("(", "");
			String tel2 = tel1.replace(")", "");
			String tel3 = tel2.replace("-", "");
			String tel4 = tel3.replace(" ", "");
			String tel5 = tel4.replace(" ", "");
			
			String senhaLogin = request.getParameter("senhaLogin");
			String senhaAcesso = request.getParameter("senhaAcesso");
			
			if( (nome != null) && (cpf != null) && (dataNasc != null) && (endereco != null) && (telefone != null) && (senhaLogin != null) && (senhaAcesso != null) ){
				URL url = new URL("http://10.87.207.6:8080/WebService/service");
				
				JSONObject json = new JSONObject();
				json.put("nome", nome);
				json.put("cpf", cpfzao);
				json.put("dataNasc", dataNasc1);
				json.put("endereco", endereco);
				json.put("telefone", tel5);
				json.put("senhaLogin", senhaLogin);
				json.put("senhaAcesso", senhaAcesso);
				
				HttpURLConnection con = (HttpURLConnection) url.openConnection();
				con.setRequestMethod("POST");
				con.setDoOutput(true);
				
				String parametros = "id=2&tipo="+tipagem+"&valores="+json.toString();
				DataOutputStream wr = new DataOutputStream(con.getOutputStream());
				wr.writeBytes(parametros);
				
				BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
				
				String apnd = "", linha = "";
	
				while((linha = br.readLine()) != null) apnd += linha;
				
				JSONObject jon = new JSONObject(apnd);
				
				if(jon.has("cod")){
					int cod = jon.getInt("cod");
					
					if(cod == 101){
						out.print("<script>alert('Parâmetros fora do escopo.')</script>");
					}else if(cod == 102){
						out.print("<script>alert('Senha de acesso invalida.')</script>");
					}else if(cod == 103){
						out.print("<script>alert('CPF Inválido.')</script>");
					}else if(cod == 104){
						out.print("<script>alert('Data inválida.')</script>");
					}else if(cod == 105){
						out.print("<script>alert('Falha ao inserir.')</script>");
					}else if(cod == 106){
						out.print("<script>alert('CPF inválido.')</script>");
					}else if(cod == 001){
						out.print("<script>alert('Tipo não informado.')</script>");
					}else if(cod == 002){
						out.print("<script>alert('Valores não recebidos.')</script>");
					}else if(cod == 003){
						out.print("<script>alert('ID não informado.')</script>");
					}else if(cod == 007){
						out.print("<script>alert('Campo não encontrado.')</script>");
					}else{
						out.print("<script>alert('Conta não existe.')</script>");
					}
				}else{
					out.print("<script>alert('Número da sua conta é: "+jon.getString("numero_conta")+". Anote-a ou logue para saber sua conta.')</script>");
				}
			}
		}
	
      out.write("\r\n");
      out.write("\t<div class=\"navConteudo pb-4\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light\" id=\"Letreiro\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\"><img src=\"img/logot.png\" id=\"imgNav\"\r\n");
      out.write("\t\t\t\twidth=\"390px\" height=\"90px\"></a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler btn btn-light\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon btn btn-light bg-light\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<div class=\"form-inline ml-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown show\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false;\" style=\"text-decoration: none;\">\r\n");
      out.write("\t\t\t\t\t\t\tNavegue </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"debcre.jsp\">Débito e Crédito</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"transferencias.jsp\">Transferência</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"extrato.jsp\">Consultar\r\n");
      out.write("\t\t\t\t\t\t\t\textrato</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"pagarboleto.jsp\">Pagamento de boleto</a>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"ModalCadastro\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\t\trole=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog modal-dialog-centered modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"modal-title\">Faça seu cadastro</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body cadastroModal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divNome\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"nome1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Nome</label> <input id=\"inputNome\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"nome\" maxlength=\"152\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divCpf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cpf1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">CPF</label> <input id=\"inputCpf\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control col-11\" name=\"cpf\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divDatNasc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dataNasc1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Data de nascimento</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputNasc\" class=\"form-control col-11\" name=\"dataNasc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trequired />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divEndereco\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"endereco1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Endereço</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputEndereco\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"endereco\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divTelefone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"telefone1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Telefone</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputTelefone\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"telefone\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divSenhaAcesso\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"acesso1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Senha de acesso</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"inputAcesso\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"senhaAcesso\" required minlength=\"6\" maxlength=\"6\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divSenhaLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"login1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Senha de login</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"inputLogin\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"senhaLogin\" required minlength=\"8\" maxlength=\"16\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipagem\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"cadas\">Cadastrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"cpf\" id=\"cpf\" class=\"text-center form-control m-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"CPF\" required /> <input name=\"senhaAcessoLogin\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text-center form-control m-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Senha de acesso\" required minlength=\"6\" maxlength=\"6\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipo\" value=\"6\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-light form-control m-2 btnLogin\">Entrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipo\" value=\"out\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-light form-control m-2\">Sair</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-outline-light form-control ml-auto\" data-toggle=\"modal\" data-target=\"#ModalCadastro\" id=\"Letreiro\">Cadastre-se</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t<div class=\"partHome pt-4\">\r\n");
      out.write("\t\t<div class=\"divHome m-auto\">\r\n");
      out.write("\t\t\t<img src=\"img/background (1).svg\" height=\"800\" width=\"1200\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"partHome1 pt-4 pb-4\">\r\n");
      out.write("\t\t<div class=\"celular m-auto\">\r\n");
      out.write("\t\t\t<img src=\"img/iphone700px.png\" class=\"rounded mx-auto d-block\"\r\n");
      out.write("\t\t\t\theight=\"250\" height=\"250\"> <img src=\"img/screen.png\"\r\n");
      out.write("\t\t\t\tclass=\"screen screen1 rounded mx-auto d-block\" height=\"250\"\r\n");
      out.write("\t\t\t\theight=\"250\"> <img src=\"img/screen.png\"\r\n");
      out.write("\t\t\t\tclass=\"screen screen2 rounded mx-auto d-block\" height=\"250\"\r\n");
      out.write("\t\t\t\theight=\"250\"> <img src=\"img/screen.png\"\r\n");
      out.write("\t\t\t\tclass=\"screen screen3 rounded mx-auto d-block\" height=\"250\"\r\n");
      out.write("\t\t\t\theight=\"250\"> <img src=\"img/screen.png\"\r\n");
      out.write("\t\t\t\tclass=\"screen screen4 rounded mx-auto d-block\" height=\"250\"\r\n");
      out.write("\t\t\t\theight=\"250\"> <img src=\"img/screen.png\"\r\n");
      out.write("\t\t\t\tclass=\"screen screen5 rounded mx-auto d-block\" height=\"250\"\r\n");
      out.write("\t\t\t\theight=\"250\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"msgnCel m-auto text-center pr-2\">\r\n");
      out.write("\t\t\t<p style=\"color: whitesmoke;\">\r\n");
      out.write("\t\t\t\tConheça nosso aplicativo e tenha um acesso seguro e prático para\r\n");
      out.write("\t\t\t\tfazer a gestão da sua conta. Facilite sua vida Baixe já!<br>\r\n");
      out.write("\t\t\t\tDisponivel na PlayStore e AppleStore.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<div class=\"container pt-5\">\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header text-center\" style=\"background-color: #4794e0; color: white; border: 1px solid-transparent #4794e0\">INFORMAÇÕS DA CONTA</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2 ml-5 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Nome:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> ");
      out.print(j.getString("nome") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Endereço:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> ");
      out.print(j.getString("endereco") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2  ml-5 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Data de nascimento:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 String[] datNasc = j.getString("dataNasc").split("-"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> ");
      out.print(datNasc[2]+"/"+datNasc[1]+"/"+datNasc[0] );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Telefone:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 String[] telEdit = j.getString("telefone").split(""); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>(");
      out.print(telEdit[0]+""+telEdit[1]);
      out.write(')');
      out.write(' ');
      out.print(telEdit[2] );
      out.write(' ');
      out.print(telEdit[3]+""+telEdit[4]+""+telEdit[5]+""+telEdit[6] );
      out.write('-');
      out.print(telEdit[7]+""+telEdit[8]+""+telEdit[9]+""+telEdit[10] );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2  ml-5 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Número da conta:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> ");
      out.print(j.getString("numero_conta") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card col-5 mb-2 mt-2 pl-0 pr-0 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">Saldo:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>R$ ");
      out.print(saldo );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><br>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t#cliente{\r\n");
      out.write("\t\t\t\tdisplay: grid;\r\n");
      out.write("\t\t\t\tgrid-template-columns: 1fr 1fr 1fr 1fr;\r\n");
      out.write("\t\t\t\tgrid-template-rows: 1fr 1fr;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#botao1{\r\n");
      out.write("\t\t\t\tgrid-column-start: 2;\r\n");
      out.write("\t\t\t\tgrid-column-end: 2;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#botao2{\r\n");
      out.write("\t\t\t\tgrid-column-start: 3;\r\n");
      out.write("\t\t\t\tgrid-column-end: 3;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"cliente\">\r\n");
      out.write("\t\t\t\t<div id=\"botao1\" class=\"col mb-2\"><a href=\"debcre.jsp\"><button class=\"btn btn-outline-primary btn-lg btn-block\">Débito/Crédito</button></a></div>\r\n");
      out.write("\t\t\t\t<div id=\"botao2\" class=\"col mb-2\"><a href=\"transferencias.jsp\"><button class=\"btn btn-outline-primary btn-lg btn-block\">Transferência</button></a></div>\r\n");
      out.write("\t\t\t\t<div id=\"botao1\" class=\"col mb-2\"><a href=\"pagarboleto.jsp\"><button class=\"btn btn-outline-primary btn-lg btn-block\">Pagar boleto</button></a></div>\r\n");
      out.write("\t\t\t\t<div id=\"botao2\" class=\"col mb-2\"><a href=\"extrato.jsp\"> <button class=\"btn btn-outline-primary btn-lg btn-block\">Extrato</button></a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t<div class=\"footer text-white pt-4\">\r\n");
      out.write("\t\t<footer class=\"page-footer font-small mdb-color pt-4\">\r\n");
      out.write("\t\t\t<div class=\"container text-center text-md-left\">\r\n");
      out.write("\t\t\t\t<div class=\"row text-center text-md-left mt-3 pb-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"text-uppercase mb-4 font-weight-bold\">SmartBank</h6>\r\n");
      out.write("\t\t\t\t\t\t<p>Temos estrutura bancária completa e aprovada pelo Banco\r\n");
      out.write("\t\t\t\t\t\t\tCentral, além de mais de 50 anos de história, que possui\r\n");
      out.write("\t\t\t\t\t\t\texecutivos com grande história e notoriedade no mercado\r\n");
      out.write("\t\t\t\t\t\t\tfinanceiro brasileiro.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"text-uppercase mb-4 font-weight-bold\">Produtos</h6>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"transferencia.html\" class=\"text-white\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-decoration: none;\">Transferências</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"debcre.html\" class=\"text-white\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-decoration: none;\">Débito</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"debcre.html\" class=\"text-white\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-decoration: none;\">Crédito</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"text-uppercase mb-4 font-weight-bold\">Parceiros</h6>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://banco.bradesco/html/classic/index.shtm\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text-white\" style=\"text-decoration: none;\">Bradesco</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.bb.com.br/pbb/pagina-inicial\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text-white\" style=\"text-decoration: none;\">Banco do\r\n");
      out.write("\t\t\t\t\t\t\t\tBrasil</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mt-3 text-white\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"text-uppercase mb-4 font-weight-bold\">Contatos</h6>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> Rua Otarios Lendo, SP 092, BR\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> smartbank@gmail.com\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> 55 19 9 1234-5678\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> 55 19 9 8765-4321\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class=\"row d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-lg-8\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-lg-4 ml-lg-0\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center text-md-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-unstyled list-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn-floating btn-sm rgba-white-slight mx-1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-facebook-f\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn-floating btn-sm rgba-white-slight mx-1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn-floating btn-sm rgba-white-slight mx-1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-google-plus-g\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn-floating btn-sm rgba-white-slight mx-1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"homejs.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
