/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2020-03-04 11:33:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.*;
import java.io.*;
import org.json.*;
import java.lang.Object.*;

public final class transferencias_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("java.lang.Object");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>TRANSFERÊNCIA</title>\r\n");
      out.write("<script src=\"bootstrap/jquery/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"jQuery Mask/jquery.mask.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"transferenciacss.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"img/logo.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("a:link{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"conteudo\">\r\n");
      out.write("\t");

		String nb = "nobody";
		String whois = (session.getAttribute("usuario") == null) ? "{\"nobody\":"+nb+"}" : session.getAttribute("usuario").toString();
		JSONObject j = new JSONObject(whois);
		String saldo = "";
		String conta_origem = request.getParameter("conta_origem");
		String conta_destino = request.getParameter("conta_destino");		
		String valor = request.getParameter("valor");
		
		if ((conta_origem != null) && (conta_destino != null) && (valor != null)) {
			String data = request.getParameter("data");
			String data1 = data.replace("/", ""); 
			
			URL url = new URL("http://10.87.203.16:8080/WebService/service");

			JSONObject json = new JSONObject();
			json.put("conta_origem", conta_origem);
			json.put("conta_destino", conta_destino);
			json.put("data", data1);
			json.put("valor", valor);

			HttpURLConnection con = (HttpURLConnection) url.openConnection();
			con.setRequestMethod("POST");
			con.setDoOutput(true);

			String parametros = "id=2&tipo=5&valores=" + json.toString();
			DataOutputStream wr = new DataOutputStream(con.getOutputStream());
			wr.writeBytes(parametros);

			BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));

			String apnd = "", linha = "";

			while ((linha = br.readLine()) != null) apnd += linha;

			saldo = apnd;

			JSONObject jon = new JSONObject(apnd);
			
			if(jon.has("cod")){
				int cod = jon.getInt("cod");
				
				if(cod == 301){
					out.print("<script>alert('Saldo insuficiente.')</script>");
				}else{
					out.print("<script>alert('Falha ao inserir.')</script>");
				}
			}else{
				int saldoTrans = jon.getInt("saldo");
				out.print("<script>alert('Transferência feita com sucesso. Saldo atual: "+saldoTrans+"')</script>");
			}
		}
		
	String tipo = request.getParameter("tipo");
		
		if(tipo != null){
			if(tipo.equals("6")){
				URL url = new URL("http://10.87.203.16:8080/WebService/service");
				
				String cpf = request.getParameter("cpf");
				String cpf1 = cpf.replace(".", "");
				String cpfzao = cpf1.replace("-", "");
				
				String senhaAcesso = request.getParameter("senhaAcessoLogin");
				String sair = request.getParameter("sair");
				
				JSONObject json = new JSONObject();
				json.put("documento", cpfzao);
				json.put("senhaAcesso", senhaAcesso);
					
				HttpURLConnection con = (HttpURLConnection) url.openConnection();
				con.setRequestMethod("POST");
				con.setDoOutput(true);
				
				String parametros = "id=2&tipo=6&valores="+json.toString();
				DataOutputStream wr = new DataOutputStream(con.getOutputStream());
				wr.writeBytes(parametros);
				
				BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
				
				String apnd = "", linha = "";
				
				while((linha = br.readLine()) != null) apnd += linha;
				
				JSONObject obj = new JSONObject(apnd);
				String nome = obj.getString("nome");
				String numero = obj.getString("numero_conta");
				
				HttpSession hs = request.getSession();
				hs.setAttribute("usuario", apnd);	
				response.sendRedirect("home.jsp");
			}else{
				HttpSession hs = request.getSession();
				hs.invalidate();
				response.sendRedirect("home.jsp");
			}
		}
		
		String tipagem = request.getParameter("tipagem");
		String recebedor = "";
		
		if(tipagem != null){
			String nome = request.getParameter("nome");
			
			String cpf = request.getParameter("cpf");
			String cpf1 = cpf.replace(".", "");
			String cpfzao = cpf1.replace("-", "");
			
			String dataNasc = request.getParameter("dataNasc");
			String dataNasc1 = dataNasc.replace("/", "");
			
			String endereco = request.getParameter("endereco");
			
			String telefone = request.getParameter("telefone");
			String tel1 = telefone.replace("(", "");
			String tel2 = tel1.replace(")", "");
			String tel3 = tel2.replace("-", "");
			String tel4 = tel3.replace(" ", "");
			String tel5 = tel4.replace(" ", "");
			
			String senhaLogin = request.getParameter("senhaLogin");
			String senhaAcesso = request.getParameter("senhaAcesso");
			
			if( (nome != null) && (cpf != null) && (dataNasc != null) && (endereco != null) && (telefone != null) && (senhaLogin != null) && (senhaAcesso != null) ){
				URL url = new URL("http://10.87.203.16:8080/WebService/service");
				
				JSONObject json = new JSONObject();
				json.put("nome", nome);
				json.put("cpf", cpfzao);
				json.put("dataNasc", dataNasc1);
				json.put("endereco", endereco);
				json.put("telefone", tel5);
				json.put("senhaLogin", senhaLogin);
				json.put("senhaAcesso", senhaAcesso);
				
				HttpURLConnection con = (HttpURLConnection) url.openConnection();
				con.setRequestMethod("POST");
				con.setDoOutput(true);
				
				String parametros = "id=2&tipo="+tipagem+"&valores="+json.toString();
				DataOutputStream wr = new DataOutputStream(con.getOutputStream());
				wr.writeBytes(parametros);
				
				BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
				
				String apnd = "", linha = "";
	
				while((linha = br.readLine()) != null) apnd += linha;
				
				JSONObject jon = new JSONObject(apnd);
				
				if(jon.has("cod")){
					
					int codwrong= jon.getInt("cod");
					
					if(codwrong == 301){
						out.print("<script>Saldo insuficiente.')</script>");
					}else{
						out.print("<script>Falha ao inserir .')</script>");
					}
				}
			}
		}
	
      out.write("\r\n");
      out.write("\t<div class=\"navConteudo\">\r\n");
      out.write("\t\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t\t\t<p class=\"text-center pt-3 text-white\"><a href=\"home.jsp\">LOGUE</a> EM SUA CONTA.</p>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light\" id=\"Letreiro\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\"><img src=\"img/logot.png\" id=\"imgNav\"\r\n");
      out.write("\t\t\t\twidth=\"390px\" height=\"90px\"></a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<div class=\"form-inline ml-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown show\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false;\"> Mais </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"debcre.jsp\">Débito e Crédito</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"transferencia.jsp\">Transferência</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"extrati.jsp\">Consultar\r\n");
      out.write("\t\t\t\t\t\t\t\textrato</a>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"ModalCadastro\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\t\trole=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog modal-dialog-centered modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"modal-title\">Faça seu cadastro</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body cadastroModal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divNome\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"nome1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Nome</label> <input id=\"inputNome\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"nome\" maxlength=\"152\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divCpf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"cpf1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">CPF</label> <input id=\"inputCpf\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control col-11\" name=\"cpf\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divDatNasc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dataNasc1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Data de nascimento</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputNasc\" class=\"form-control col-11\" name=\"dataNasc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trequired />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divEndereco\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"endereco1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Endereço</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputEndereco\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"endereco\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divTelefone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"telefone1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Telefone</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"inputTelefone\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"telefone\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divSenhaAcesso\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"acesso1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Senha de acesso</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"inputAcesso\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"senhaAcesso\" required maxlength=\"6\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group divSenhaLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"login1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"mr-auto\">Senha de login</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"inputLogin\" class=\"form-control col-11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"senhaLogin\" required minlength=\"8\" maxlength=\"16\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipagem\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"cadas\">Cadastrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"cpf\" id=\"cpf\" class=\"text-center form-control m-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"CPF\" required /> <input name=\"senhaAcessoLogin\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text-center form-control m-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Senha de acesso\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipo\" value=\"6\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-light form-control m-2 btnLogin\">Entrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"tipo\" value=\"out\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-light form-control m-2\">Sair</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
if(whois.equals("{\"nobody\":"+nb+"}")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-outline-light form-control ml-auto\" data-toggle=\"modal\" data-target=\"#ModalCadastro\" id=\"Letreiro\">Cadastre-se</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"partTrans mt-2\">\r\n");
      out.write("\t\t<form class=\"divTrans\" method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label id=\"cntOrg\" class=\"text-white\">Informe a conta de origem</label> \r\n");
      out.write("\t\t\t\t");
 JSONObject jo = new JSONObject(whois); 
      out.write("\r\n");
      out.write("\t\t\t\t<input id=\"cntOrigem\" class=\"form-control\" type=\"text\" placeholder=\"Conta origem\" name=\"conta_origem\" readonly value=\"");
      out.print(jo.getString("numero_conta") );
      out.write("\" required/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"text-white\">Informe a conta de destino</label> \r\n");
      out.write("\t\t\t\t<input id=\"cntDestino\" class=\"form-control\" type=\"text\" placeholder=\"Conta destino\" name=\"conta_destino\" required/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"text-white\">Informe a data para a transferência</label> \r\n");
      out.write("\t\t\t\t<input id=\"data\" class=\"form-control\" type=\"text\" placeholder=\"Data\" name=\"data\" required/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"text-white\">Informe o valor da transferência</label> \r\n");
      out.write("\t\t\t\t<input id=\"valor\" class=\"form-control\" type=\"text\" placeholder=\"Valor\" name=\"valor\" required/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button id=\"btntrans\" class=\"form-control btn btn-primary\"\r\n");
      out.write("\t\t\t\ttype=\"submit\">Enviar</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"transferenciajs.js\"></script>\r\n");
      out.write("\t");

		if ((conta_origem != null) && (conta_destino != null) && (valor != null)) {
			JSONObject obj = new JSONObject(saldo);
	
      out.write("\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t//var booleana = confirm(\"Transferência feita com sucesso.\");\r\n");
      out.write("\t\t\t//booleana;\r\n");
      out.write("\t\t\t//if(booleana == true){\r\n");
      out.write("\t\t\t\t//window.location.href = 'home.jsp';\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t");

		}
	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
